server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 30s

## logback
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    file: "[dev] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"
    console: "[dev] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"

spring:
  profiles:
    active: dev
    include: core

  data:
    redis:
      repositories:
        enabled: false

#  redis:
#    port: 6379
#    host: localhost


