spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # jpa
  jpa:
    open-in-view: false # ? ???? ???? ???? ?? ??, ??? ??? ?? ??? ?? false ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        #        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        order_inserts: true
        order_updates: true
        hbm2ddl.auto: validate # validate or none
        generate-ddl: false


