spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # jpa
  jpa:
    open-in-view: false # View단에서도 DB을 연결 해서 지연로딩이 가능하게 함.
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        #        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        order_inserts: true
        order_updates: true
        hbm2ddl.auto: validate # validate or none
        generate-ddl: false

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${mail.username}
#    password: ${mail.password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true


