server:
  port: 18080
  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 30s

## logback
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    file: "[local] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"
    console: "[local] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"

spring:
  profiles:
    active: local
    include: core

  data:
    redis:
      repositories:
        enabled: false

  redis:
    port: 6379
    host: localhost

#  archi:
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/archi?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#      username: root
#      password: 1234
#      hikari:
#        connectionTimeout: 3000
#        maximumPoolSize: 30
#        maxLifetime: 1800000
#        poolName: HikariCP
#        readOnly: false
#        connectionTestQuery: SELECT 1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/archi
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
