
ALTER TABLE CATEGORY
    ADD COLUMN CREATE_USER VARCHAR(255) NOT NULL,
    ADD COLUMN UPDATE_USER VARCHAR(255),
    ADD COLUMN ACTIVE_YN ENUM('Y', 'N') DEFAULT 'Y' NOT NULL,
    ADD COLUMN CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN UPDATED_AT DATETIME DEFAULT NULL;