ALTER TABLE `CONTENT`
DROP COLUMN `LIKE`;

CREATE TABLE CONTENT_LIKE (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      USER_ID varchar(255) NOT NULL,
                      CONTENT_ID BIGINT NOT NULL,
                      CONSTRAINT FK_CONTENT_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES USER(id),
                      CONSTRAINT FK_CONTENT_LIKE_CONTENT FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(id)
);

